name: Build Sourcemapper

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Clone sourcemapper
        run: git clone https://github.com/denandz/sourcemapper

      - name: Change to sourcemapper directory
        run: cd sourcemapper && go get && go build

      - name: Verify build output
        run: |
          if [ -f "sourcemapper/sourcemapper" ]; then
            echo "Build successful!"
          else
            echo "Build failed." && exit 1
          fi

      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          name: sourcemapper-binary
          path: ./sourcemapper/sourcemapper

  download-artifact:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: sourcemapper-binary

      - name: Show downloaded artifact
        run: ls -l
