name: Build and Download Sourcemapper Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20' # Or your desired Go version

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: |
          go build -o sourcemapper

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sourcemapper-binary
          path: sourcemapper

  download:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: sourcemapper-binary
          path: .

      - name: List files
        run: ls -l
